
env:
  grid_x: 5
  grid_y: 5
  num_colors: 10
  num_actions: 28 # should get it from env
  project_dir: "/home/bjlee/arc_exp"
  train_paths: ["ICLR_DT/ARC_Data/diagonal_flip/train", "ICLR_DT/ARC_Data/gravity/train", "ICLR_DT/ARC_Data/stretch/train", "ICLR_DT/ARC_Data/tetris/train"]
  test_paths: ["ICLR_DT/ARC_Data/diagonal_flip/test", "ICLR_DT/ARC_Data/gravity/test", "ICLR_DT/ARC_Data/stretch/test", "ICLR_DT/ARC_Data/tetris/test"]

model:
  n_layer: 16
  n_head: 8
  n_embd: 256
  embd_pdrop: 0.1
  resid_pdrop: 0.1
  attn_pdrop: 0.1

train:
  total_timesteps: 1000000
  max_ep_len: 100
  learning_rate: 0.0005
  batch_size: 64
  save_cycle: 50
  weight_decay: 0.1
  beta1: 0.9
  beta2: 0.95
  tau: 0.005
  epsilon: 0.2
  dec_epsilon: 0.00005
  min_epsilon: 0.1
  gamma: 0.99
  gpu_num: 0

logging:
  logging_dir: "exps/"
  exp_type: "dqn"
  print_data: False
  use_tb: True
  log_interval: 1000
  num_evaluations: 20
